---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-carleton-services

resources:
- ns-carleton-services.yaml
- senderTOm1-ns.yaml
- m11TOm21-ns.yaml
- m12TOm22-ns.yaml
- m2TOreceiver-ns.yaml
- sender.yaml
- middlebox1.yaml
- middlebox2.yaml
- receiver.yaml